import { describe, expect, it } from 'vitest';
import { decideAnonymousTransition, isIdentifiedDistinctId } from '../consent-state';

const UUID = '0192a3b4-5c6d-7e8f-9a0b-1c2d3e4f5a6b'; // uuidv7, as generated by the pixel / posthog-js
const EMAIL = 'jane@example.com';

describe('isIdentifiedDistinctId', () => {
  it('treats UUIDs, empty strings and non-strings as anonymous', () => {
    expect(isIdentifiedDistinctId(UUID)).toBe(false);
    expect(isIdentifiedDistinctId(UUID.toUpperCase())).toBe(false);
    expect(isIdentifiedDistinctId('')).toBe(false);
    expect(isIdentifiedDistinctId(undefined)).toBe(false);
    expect(isIdentifiedDistinctId(null)).toBe(false);
    expect(isIdentifiedDistinctId(42)).toBe(false);
  });

  it('treats emails and customer ids as identified', () => {
    expect(isIdentifiedDistinctId(EMAIL)).toBe(true);
    expect(isIdentifiedDistinctId('7654321098765')).toBe(true);
  });
});

describe('decideAnonymousTransition', () => {
  it('resets when the marker is absent but the blob holds an identified id (theme posthog-js / stale pixel identify)', () => {
    expect(decideAnonymousTransition({ anonymous: true, marker: null, storedDistinctId: EMAIL })).toEqual({
      reset: true,
      marker: 'true',
    });
  });

  it('does not reset an anonymous UUID id — that would wipe $sesid / $device_id for every consent-refused visitor', () => {
    expect(decideAnonymousTransition({ anonymous: true, marker: null, storedDistinctId: UUID })).toEqual({
      reset: false,
      marker: 'true',
    });
    expect(decideAnonymousTransition({ anonymous: true, marker: 'true', storedDistinctId: UUID })).toEqual({
      reset: false,
      marker: null,
    });
  });

  it("resets on the identified → anonymous flip (marker 'false'), even with a UUID id", () => {
    expect(decideAnonymousTransition({ anonymous: true, marker: 'false', storedDistinctId: UUID })).toEqual({
      reset: true,
      marker: 'true',
    });
  });

  it("resets when the marker already says 'true' but an identified id persists", () => {
    expect(decideAnonymousTransition({ anonymous: true, marker: 'true', storedDistinctId: EMAIL })).toEqual({
      reset: true,
      marker: null,
    });
  });

  it('never resets an identified visitor', () => {
    for (const marker of [null, 'true', 'false'] as const) {
      for (const storedDistinctId of [EMAIL, UUID, undefined]) {
        expect(decideAnonymousTransition({ anonymous: false, marker, storedDistinctId }).reset).toBe(false);
      }
    }
  });

  it('writes the marker only when it differs from the current state', () => {
    expect(decideAnonymousTransition({ anonymous: false, marker: null, storedDistinctId: UUID }).marker).toBe('false');
    expect(decideAnonymousTransition({ anonymous: false, marker: 'true', storedDistinctId: UUID }).marker).toBe('false');
    expect(decideAnonymousTransition({ anonymous: false, marker: 'false', storedDistinctId: UUID }).marker).toBeNull();
    expect(decideAnonymousTransition({ anonymous: true, marker: 'true', storedDistinctId: UUID }).marker).toBeNull();
  });
});
